default: &default
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  username: postgres
  password: root

development:
  <<: *default
  database: shift_care_development

test:
  <<: *default
  database: shift_care_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
